"""Tests for unified Learning Buddy identity resolution."""

from __future__ import annotations

import os
from pathlib import Path

from pytest import MonkeyPatch

from companion.character_identity import CharacterIdentity, resolve_character_identity
from companion.character_judge import CharacterJudgeResult
from companion.schema import AvatarConfig, CharacterStyleSheet, LearnerProfile


def _ian_profile(equipped_items: dict[str, str] | None = None) -> LearnerProfile:
    return LearnerProfile(
        name="Ian",
        grade_level="1",
        avatar=AvatarConfig(
            base_character="ian_learning_buddy",
            equipped_items=equipped_items or {},
            style_sheet=CharacterStyleSheet(
                character_block="Ian has rainbow spiky hair and a blue lightning shirt.",
                reference_image_dir="assets/style_sheets/ian_roblox_buddy",
                scene_guidelines="Use calm printable learning panels.",
                item_style_notes="Accessories must not hide Ian's hair or lightning shirt.",
                theme_id="roblox_obby",
            ),
        ),
    )


def test_character_identity_model_round_trips() -> None:
    identity = CharacterIdentity(
        base_character="ian_learning_buddy",
        base_image_path="assets/characters/ian_learning_buddy.png",
        reference_image_dir="assets/style_sheets/ian_roblox_buddy",
        canonical_reference_path="assets/style_sheets/ian_roblox_buddy/ref_front_character_crop.png",
        pose_reference_path="assets/style_sheets/ian_roblox_buddy/pose_pointing.png",
        character_block="Ian block",
        scene_guidelines="Calm scene",
        item_style_notes="Keep items readable",
        equipped_items={"backpack": "brown_backpack"},
        identity_version="identity_v1_test",
    )

    restored = CharacterIdentity.model_validate_json(identity.model_dump_json())

    assert restored == identity


def test_character_judge_result_model_round_trips() -> None:
    result = CharacterJudgeResult(
        available=True,
        approved=False,
        score=4,
        issues=["hair color changed"],
        judge="gemini",
    )

    restored = CharacterJudgeResult.model_validate_json(result.model_dump_json())

    assert restored == result


def test_character_judge_accepts_boolean_approval_values() -> None:
    from companion import character_judge

    approved = character_judge._coerce_result(
        {"approved": True, "score": 9, "issues": []},
        "test",
    )
    rejected = character_judge._coerce_result(
        {"approved": False, "score": 3, "issues": ["identity changed"]},
        "test",
    )
    passed_alias = character_judge._coerce_result(
        {"passed": True, "score": 8, "issues": []},
        "test",
    )

    assert approved.approved is True
    assert rejected.approved is False
    assert passed_alias.approved is True


def test_character_judge_rejects_string_false_approval_values() -> None:
    from companion import character_judge

    result = character_judge._coerce_result(
        {"approved": "false", "score": 8, "issues": []},
        "test",
    )

    assert result.approved is False


def test_character_judge_rejects_malformed_or_missing_approval_values() -> None:
    from companion import character_judge

    malformed = character_judge._coerce_result(
        {"approved": "definitely", "score": 8, "issues": []},
        "test",
    )
    missing = character_judge._coerce_result(
        {"score": 8, "issues": []},
        "test",
    )
    string_passed = character_judge._coerce_result(
        {"passed": "no", "score": 8, "issues": []},
        "test",
    )

    assert malformed.approved is False
    assert missing.approved is False
    assert string_passed.approved is False


def test_variant_judging_delegates_to_shared_character_judge(monkeypatch: MonkeyPatch) -> None:
    from companion import generate_overlays

    observed: dict[str, object] = {}

    def fake_judge(
        reference_bytes: bytes,
        generated_bytes: bytes,
        criteria: list[str],
    ) -> CharacterJudgeResult:
        observed["reference"] = reference_bytes
        observed["generated"] = generated_bytes
        observed["criteria"] = criteria
        return CharacterJudgeResult(
            available=True,
            approved=True,
            score=8,
            issues=["minor edge cleanup"],
            judge="fake",
        )

    monkeypatch.setattr(generate_overlays, "judge_character_consistency", fake_judge)

    verdict = generate_overlays._judge_variant(
        b"reference bytes",
        b"generated bytes",
        {"backpack": "brown_backpack"},
    )

    assert verdict == {
        "passed": True,
        "score": 8,
        "issues": ["minor edge cleanup"],
    }
    assert observed["reference"] == b"reference bytes"
    assert observed["generated"] == b"generated bytes"
    criteria = observed["criteria"]
    assert isinstance(criteria, list)
    assert any("same character" in criterion.lower() for criterion in criteria)


def test_resolver_returns_base_path_from_profile_base_character() -> None:
    identity = resolve_character_identity(_ian_profile(), "roblox_obby")

    assert identity.base_character == "ian_learning_buddy"
    assert identity.base_image_path == str(Path("assets/characters/ian_learning_buddy.png"))


def test_resolver_loads_reference_dir_and_canonical_reference() -> None:
    identity = resolve_character_identity(_ian_profile(), "roblox_obby")

    assert identity.reference_image_dir == "assets/style_sheets/ian_roblox_buddy"
    assert identity.canonical_reference_path == (
        "assets/style_sheets/ian_roblox_buddy/ref_front_character_crop.png"
    )


def test_resolver_chooses_pose_specific_reference() -> None:
    identity = resolve_character_identity(_ian_profile(), "roblox_obby", pose="pointing")

    assert identity.pose_reference_path == "assets/style_sheets/ian_roblox_buddy/pose_pointing.png"


def test_resolver_includes_equipped_items_in_identity_version() -> None:
    plain = resolve_character_identity(_ian_profile(), "roblox_obby")
    backpack = resolve_character_identity(
        _ian_profile({"backpack": "brown_backpack"}),
        "roblox_obby",
    )

    assert backpack.equipped_items == {"backpack": "brown_backpack"}
    assert backpack.identity_version != plain.identity_version


def test_resolver_includes_scene_guidelines_and_item_notes() -> None:
    identity = resolve_character_identity(_ian_profile(), "roblox_obby")

    assert "calm printable" in identity.scene_guidelines
    assert "lightning shirt" in identity.item_style_notes
    assert "rainbow spiky hair" in identity.character_block


def test_resolver_does_not_fall_back_to_rainbow_when_ian_exists() -> None:
    identity = resolve_character_identity(_ian_profile(), "roblox_obby")

    assert identity.base_character == "ian_learning_buddy"
    assert identity.base_image_path is not None
    assert "rainbow_roblox" not in identity.base_image_path


def test_selected_reference_content_changes_identity_version(tmp_path: Path) -> None:
    ref_dir = tmp_path / "refs"
    ref_dir.mkdir()
    front_ref = ref_dir / "ref_front_character_crop.png"
    front_ref.write_bytes(b"first reference bytes")
    profile = LearnerProfile(
        name="Ian",
        grade_level="1",
        avatar=AvatarConfig(
            base_character="ian_learning_buddy",
            style_sheet=CharacterStyleSheet(
                character_block="Ian has rainbow spiky hair.",
                reference_image_dir=str(ref_dir),
            ),
        ),
    )

    first = resolve_character_identity(profile, "roblox_obby")
    front_ref.write_bytes(b"changed reference bytes")
    second = resolve_character_identity(profile, "roblox_obby")

    assert second.identity_version != first.identity_version


def test_selected_reference_touch_keeps_identity_version_stable(tmp_path: Path) -> None:
    ref_dir = tmp_path / "refs"
    ref_dir.mkdir()
    front_ref = ref_dir / "ref_front_character_crop.png"
    front_ref.write_bytes(b"same reference bytes")
    profile = LearnerProfile(
        name="Ian",
        grade_level="1",
        avatar=AvatarConfig(
            base_character="ian_learning_buddy",
            style_sheet=CharacterStyleSheet(
                character_block="Ian has rainbow spiky hair.",
                reference_image_dir=str(ref_dir),
            ),
        ),
    )

    first = resolve_character_identity(profile, "roblox_obby")
    stat = front_ref.stat()
    os.utime(
        front_ref,
        ns=(stat.st_atime_ns + 1_000_000_000, stat.st_mtime_ns + 1_000_000_000),
    )
    second = resolve_character_identity(profile, "roblox_obby")

    assert second.identity_version == first.identity_version
